# Generated by Django 4.2.17 on 2024-12-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subclass', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_l', models.CharField(max_length=128, unique=True)),
                ('squad', models.CharField(max_length=128)),
                ('home', models.TextField(blank=True, null=True)),
                ('food', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='animals')),
                ('subclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.AnimalCategory')),
            ],
        ),
    ]
